name: Terraform Provider Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build Terraform Provider
        run: |
          go mod tidy
          go build -o terraform-provider-custom

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: terraform-provider-custom
